services:
  postgres:
    image: postgres:16-alpine
    container_name: platform-postgres
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER:-postgres}"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    volumes:
      - /data/platform/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?error}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
    networks:
      - dokploy-network
    labels:
      - "traefik.enable=false"

networks:
  dokploy-network:
    external: true
